# Generated by Django 3.1.7 on 2021-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210428_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mbarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hervos', models.CharField(max_length=254)),
                ('regisc', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
