# Generated by Django 3.1.7 on 2021-04-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210329_1708'),
        ('checkout', '0003_ordertwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertwo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='county',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='ordertwo',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='ordertwo',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
